### ISSUE TITLE
Documentation - Milestone update

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#110]
# Description

Updates generales que se deben de hacer:

- [ ] Changes to the previous submission must be clearly visible. Use a different background color, change bars in the page margin, or other ways to clearly indicate the changes.

- [ ] The log book gives an overview of the changes (but not the full changed content) since the last submission.

- [ ] The actual changes, new developments, etc are integrated into the overall document.

- [ ] All the criteria where the previous submission did not follow the guidelines have been improved.

- [ ] Any additions and changes follow the guidelines already established for the milestone 1 submission.

- [ ] Progress in the implementation has been made: there are completed features that are implemented end-to-end and that have a high value to the users. The completion of the feature is evidenced by passing acceptance/end-to-end tests.

- [ ] Progress has been made in all phases of development: domain description, requirements prescription, design, …

Aquí les dejo la rubrica como parte de lo que se debe mejorar en la documentación antes de añadir lo correspondiente.

![Image](https://github.com/uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application/assets/108200951/c13761f2-9191-4d2b-a8ab-32d307ee270e)

**Comment by AlfredoSoto1** [comment]
Recuerden, todo lo viejo que se modifique tiene que estar diferenciado a lo nuevo que se añada. Esto puede ser con distintos highliters en el documento.

**Comment by AlfredoSoto1** [comment]
Recalco una vez más para que no se cometa el mismo error. Recuerden que lo nuevo debe de estar highlighted de un color **DISTINTO** a lo que se valla a modificar del documento (lo del milestone 1). Eso fue unas de las criticas que el profe dejó.
