### ISSUE TITLE
Road Map Design

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#65]
# Description
The Road Map is where the user can see their progress(xp) and the current level that they are. The level represent which station he has already unlocked. Each station has a workout to be done and should redirect the user to that screen.

# Key Features

### Page Navigation Functionality:

- [ ] Each station should include the functionality to switch to the page where the workout progress/action is tracked.
- [ ] It should incorporate anchor buttons, which will conveniently redirect users to essential sections such as RoadMap and Exercises/Workout selection.

### Display User Progress:

- [x] The current level of the user 
- [x] The current progress of the user (a progress bar)
- [x] The stations that get unlocked after the user pass a level
