### ISSUE TITLE
Milestone 1 Feedback review

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#71]
# Description

- Review the feedback given in moodle from the professor of milestone 1
- Create a list of the things that need improvement from what the professor suggests
- After creating a list of the things that need improvement, reply to this issue with the
list so that later a new issue can be created to improve the documentation.

**Comment by AlfredoSoto1** [comment]
Hello team! Como van con el feedback review?

Tengo otro task que les voy a asignar para que actualicen  la documentación ya existente con el feedback del profe. Also, en otro issue que les tengo asignado a ustedes es que para los que vallan a trabajar en la documentación del milestone 2, ustedes se mantengan en contacto con ellos para que les brinden conocimiento acerca del feedback del profe para que no se cometan los mismos errores en la nueva version de la documentación.

**Comment by AlfredoSoto1** [comment]
Refieranse al [Issue #89 ] para que estén al tanto y mantengan contacto con los devs encargados de la documentación del milestone 2

**Comment by AlfredoSoto1** [comment]
Aqui les dejo el link al documento para que puedan actualizarlo
https://docs.google.com/document/d/1STYnwFFMQANmVZkxhREbYkdxxjH-6x99r3gTli65Kqc/edit?usp=sharing

**Comment by YampierFernandez** [comment]
List of changes to make:

-Change the scope and span to include domain engineering, requirements engineering, software design, etc. and the span should go into more detail and be more specific.

- The synopsis need to cover aspects of the whole project.

-Adjust the domain talk about things in the domain that are relevant to the project in a way that’s independent of any implementation. We’re talking here about domain concepts and how they relate to one another and it should be clear that these concepts cannot only be entities, but also actions, events, and behaviors.

-The other activities part shouldn’t be its own section but the content should be moved to existing areas where it’s relevant (In other word remove the other activities section and take the points mentioned to other sections).

-Adjust the derived goals to be a little more “out of the way” but still easy to implement.

- In the areas where we use diagrams we need to add text that gives context to those diagrams.

-We need to add a legend to our “non-standard graphical language”

-In the terminology we need to add operations that can be done with the entities mentioned, behaviors and events. Entities, actions (or functions), events, and behaviors must be in te same section not separate.

-Change StopWatch to TimerTick 

-When you are describing domain behaviors then there can not be a user. Instead, we can talk about an exerciser starting, stopping, or resetting a timer, but not about a user interacting with any buttons.

-Overlap between behaviors 

- “The function signatures should not go into a section by themselves: their purpose is to complement the understanding of the domain actions and so they should be there with the description of the domain actions.”

-Don’t write “as a user” in user stories, because it’s implied. Specify the type of user.

-The player profile requirement should be split into parts and expanded.

- Requirements must be measurable.

- Traceability is not verification.

**Comment by oscaroflores** [comment]
List of changes to make:

- [ ] Change the scope and span to include domain engineering, requirements engineering, software design, etc. and the span should go into more detail and be more specific.
- [ ] The synopsis need to cover aspects of the whole project.
- [ ] Adjust the domain talk about things in the domain that are relevant to the project in a way that’s independent of any implementation. We’re talking here about domain concepts and how they relate to one another and it should be clear that these concepts cannot only be entities, but also actions, events, and behaviors.
- [ ] The other activities part shouldn’t be its own section but the content should be moved to existing areas where it’s relevant (In other word remove the other activities section and take the points mentioned to other sections).
- [ ] Adjust the derived goals to be a little more “out of the way” but still easy to implement.
- [ ] In the areas where we use diagrams we need to add text that gives context to those diagrams.
- [ ] We need to add a legend to our “non-standard graphical language”
- [ ] In the terminology we need to add operations that can be done with the entities mentioned, behaviors and events. Entities, actions (or functions), events, and behaviors must be in te same section not separate.
- [ ] Change StopWatch to TimerTick
- [ ] When you are describing domain behaviors then there can not be a user. Instead, we can talk about an exerciser starting, stopping, or resetting a timer, but not about a user interacting with any buttons.
- [ ] Overlap between behaviors
- [ ] The function signatures should not go into a section by themselves: their purpose is to complement the understanding of the domain actions and so they should be there with the description of the domain actions.”
- [ ] Don’t write “as a user” in user stories, because it’s implied. Specify the type of user.
- [ ] The player profile requirement should be split into parts and expanded.
- [ ] Requirements must be measurable.
- [ ] Traceability is not verification.
