### ISSUE TITLE
Prepare a video proposal for milestone 2

### ISSUE THREAD

**Issue by AlfredoSoto1** [uprm-inso4101-2023-2024-S1/semester-project-fitquest-gameified-fitness-application#88]
# Description
Prepare a video proposal containing the new features set for this milestone (2). This video must be like the video proposal of the first milestone but with all the feedback from the professor given in moodle. This video must be around the same length as the first proposal. For this task we need the following:
- [x] A script
- [x] Someone to record the video
- [x] Someone to record a demo of the video
- [x] An improved version of the presentation with the professor's feedback (from milestone 1)
- [x] Build on top the updated presentation, new information about the second milestone

##  Important
We need people to start working on this before this friday. Also, to break this issue into smaller tasks we first need the people who wants to work on this issue in order to assign specific details regarding the video/proposal and the documentation in general. 

Here is the link of the documentation in case you need it for reference.
https://docs.google.com/document/d/1STYnwFFMQANmVZkxhREbYkdxxjH-6x99r3gTli65Kqc/edit?usp=sharing

**Comment by AlfredoSoto1** [comment]
# Recording and Presentation

- We are in need of an individual with proficient presentation abilities who can confidently deliver our script. Strong communication skills are vital for this task.

# Video Editing

- After the recording, we require a skilled video editor who can craft a polished and professional video presentation.

# YouTube Management

- Prepare and upload the video to youtube and create a link that can be shared with the professor.

Collaboration with the development team for [Issue #58 ] is essential.

**Comment by AlfredoSoto1** [comment]
Todos pueden trabajar en lo mismo que se dividieron para el milestone 1, pero si quieren cambiar o proponer algo pueden escribir directamente aquí en este issue

**Comment by Jeimy-S** [comment]
Presentation to edit: https://docs.google.com/presentation/d/1SDDZb4rVvmGV6H48nBXXcm41uroqNvPizdK7qS8tBZI/edit?usp=sharing

Script to edit: https://docs.google.com/document/d/1qqPggS0pm14W4ARn0kl0qxlHnHwzlruzLYY-0qu_fuo/edit?usp=sharing

**Comment by Chosen-Juan1** [comment]
As an update, the professor stated that the presentation (which includes the video) is for Monday, not Friday. The documentation is for Friday.

**Comment by Chosen-Juan1** [comment]
I have recorded, edited, and posted the video on Moodle. This issue should be complete now.
